<!DOCTYPE qhelp SYSTEM "qhelp.dtd">
<qhelp>
 <section title="Description">
  <p>
   Under certain circumstances, terminating a destructor,
   <code>
    operator delete
   </code>
   , or
   <code>
    operator delete[]
   </code>
   by throwing an exception can trigger
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/BB.+Definitions#BB.Definitions-undefinedbehavior">
    undefined behavior
   </a>
   .
  </p>
  <p>
   For instance, the C++ Standard, [basic.stc.dynamic.deallocation], paragraph 3 [
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-ISO%2FIEC14882-2014">
    ISO/IEC 14882-2014
   </a>
   ], in part, states the following:
  </p>
  <blockquote>
   <p>
    If a deallocation function terminates by throwing an exception, the behavior is undefined.
   </p>
  </blockquote>
  <p>
   In these situations, the function must logically be declared
   <code>
    noexcept
   </code>
   because throwing an exception from the function can never have well-defined behavior. The C++ Standard, [except.spec], paragraph 15, states the following:
  </p>
  <blockquote>
   <p>
    A deallocation function with no explicit exception-specification is treated as if it were specified with noexcept(true).
   </p>
  </blockquote>
  <p>
   As such, deallocation functions (object, array, and placement forms at either global or class scope) must not terminate by throwing an exception. Do not declare such functions to be
   <code>
    noexcept(false)
   </code>
   . However, it is acceptable to rely on the implicit
   <code>
    noexcept(true)
   </code>
   specification or declare
   <code>
    noexcept
   </code>
   explicitly on the function signature.
  </p>
  <p>
   Object destructors are likely to be called during stack unwinding as a result of an exception being thrown. If the destructor itself throws an exception, having been called as the result of an exception being thrown, then the function
   <code>
    std::terminate()
   </code>
   is called with the default effect of calling
   <code>
    std::abort()
   </code>
   [
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-ISO%2FIEC14882-2014">
    ISO/IEC 14882-2014
   </a>
   ]
   .
   When
   <code>
    std::abort()
   </code>
   is called, no further objects are destroyed, resulting in an indeterminate program state and undefined behavior. Do not terminate a destructor by throwing an exception.
  </p>
  <p>
   The C++ Standard, [class.dtor], paragraph 3, states [
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-ISO%2FIEC14882-2014">
    ISO/IEC 14882-2014
   </a>
   ] the following:
  </p>
  <blockquote>
   <p>
    A declaration of a destructor that does not have an exception-specification is implicitly considered to have the same exception-specification as an implicit declaration.
   </p>
  </blockquote>
  <p>
   An implicit declaration of a destructor is considered to be
   <code>
    noexcept(true)
   </code>
   according to [except.spec], paragraph 14. As such, destructors must not be declared
   <code>
    noexcept(false)
   </code>
   but may instead rely on the implicit
   <code>
    noexcept(true)
   </code>
   or declare
   <code>
    noexcept
   </code>
   explicitly.
  </p>
  <p>
   Any
   <code>
    noexcept
   </code>
   function that terminates by throwing an exception violates
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR55-CPP.+Honor+exception+specifications">
    ERR55-CPP. Honor exception specifications
   </a>
   .
  </p>
 </section>
 <section title="Noncompliant Code Example">
  <p>
   In this noncompliant code example, the class destructor does not meet the implicit
   <code>
    noexcept
   </code>
   guarantee because it may throw an exception even if it was called as the result of an exception being thrown. Consequently, it is declared as
   <code>
    noexcept(false)
   </code>
   but still can trigger
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/BB.+Definitions#BB.Definitions-undefinedbehavior">
    undefined behavior
   </a>
   .
  </p>
  <sample language="cpp">
   #include &lt;stdexcept&gt;
 
class S {
  bool has_error() const;
 
public:
  ~S() noexcept(false) {
    // Normal processing
    if (has_error()) {
      throw std::logic_error("Something bad");
    }
  }
};
  </sample>
 </section>
 <section title="Noncompliant Code Example (std::uncaught_exception())">
  <p>
   Use of
   <code>
    std::uncaught_exception()
   </code>
   in the destructor solves the termination problem by avoiding the propagation of the exception if an existing exception is being processed, as demonstrated in this noncompliant code example. However, by circumventing normal destructor processing, this approach may keep the destructor from releasing important resources.
  </p>
  <sample language="cpp">
   #include &lt;exception&gt;
#include &lt;stdexcept&gt;
 
class S {
  bool has_error() const;
 
public:
  ~S() noexcept(false) {
    // Normal processing
    if (has_error() &amp;&amp; !std::uncaught_exception()) {
      throw std::logic_error("Something bad");
    }
  }
};
  </sample>
 </section>
 <section title="Noncompliant Code Example (function-try-block)">
  <p>
   This noncompliant code example, as well as the following compliant solution, presumes the existence of a
   <code>
    Bad
   </code>
   class with a destructor that can throw. Although the class violates this rule, it is presumed that the class cannot be modified to comply with this rule.
  </p>
  <sample language="cpp">
   // Assume that this class is provided by a 3rd party and it is not something
// that can be modified by the user.
class Bad {
  ~Bad() noexcept(false);
};
  </sample>
  <p>
   To safely use the
   <code>
    Bad
   </code>
   class, the
   <code>
    SomeClass
   </code>
   destructor attempts to handle exceptions thrown from the
   <code>
    Bad
   </code>
   destructor by absorbing them.
  </p>
  <sample language="cpp">
   class SomeClass {
  Bad bad_member;
public:
  ~SomeClass()
  try {
    // ...
  } catch(...) {
    // Handle the exception thrown from the Bad destructor.
  }
};
  </sample>
  <p>
   However, the C++ Standard, [except.handle], paragraph 15 [
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-ISO%2FIEC14882-2014">
    ISO/IEC 14882-2014
   </a>
   ], in part, states the following:
  </p>
  <blockquote>
   <p>
    The currently handled exception is rethrown if control reaches the end of a handler of the function-try-block of a constructor or destructor.
   </p>
  </blockquote>
  <p>
   Consequently, the caught exception will inevitably escape from the
   <code>
    SomeClass
   </code>
   destructor because it is implicitly rethrown when control reaches the end of the
   <em>
    function-try-block
   </em>
   handler.
  </p>
 </section>
 <section title="Compliant Solution">
  <p>
   A destructor should perform the same way whether or not there is an active exception. Typically, this means that it should invoke only operations that do not throw exceptions, or it should handle all exceptions and not rethrow them (even implicitly). This compliant solution differs from the previous noncompliant code example by having an explicit
   <code>
    return
   </code>
   statement in the
   <code>
    SomeClass
   </code>
   destructor. This statement prevents control from reaching the end of the exception handler. Consequently, this handler will catch the exception thrown by
   <code>
    Bad::~Bad()
   </code>
   when
   <code>
    bad_member
   </code>
   is destroyed. It will also catch any exceptions thrown within the compound statement of the
   <em>
    function-try-block
   </em>
   , but the
   <code>
    SomeClass
   </code>
   destructor will not terminate by throwing an exception.
  </p>
  <sample language="cpp">
   class SomeClass {
  Bad bad_member;
public:
  ~SomeClass()
  try {
    // ...
  } catch(...) {
    // Catch exceptions thrown from noncompliant destructors of
    // member objects or base class subobjects.

    // NOTE: Flowing off the end of a destructor function-try-block causes
    // the caught exception to be implicitly rethrown, but an explicit
    // return statement will prevent that from happening.
    return;
  }
};
  </sample>
 </section>
 <section title="Noncompliant Code Example">
  <p>
   In this noncompliant code example, a global deallocation is declared
   <code>
    noexcept(false)
   </code>
   and throws an exception if some conditions are not properly met. However, throwing from a deallocation function results in
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/BB.+Definitions#BB.Definitions-undefinedbehavior">
    undefined behavior
   </a>
   .
  </p>
  <sample language="cpp">
   #include &lt;stdexcept&gt;
 
bool perform_dealloc(void *);
 
void operator delete(void *ptr) noexcept(false) {
  if (perform_dealloc(ptr)) {
    throw std::logic_error("Something bad");
  }
}
  </sample>
 </section>
 <section title="Compliant Solution">
  <p>
   The compliant solution does not throw exceptions in the event the deallocation fails but instead fails as gracefully as possible.
  </p>
  <sample language="cpp">
   #include &lt;cstdlib&gt;
#include &lt;stdexcept&gt;
 
bool perform_dealloc(void *);
void log_failure(const char *);
 
void operator delete(void *ptr) noexcept(true) {
  if (perform_dealloc(ptr)) {
    log_failure("Deallocation of pointer failed");
    std::exit(1); // Fail, but still call destructors
  }
}
  </sample>
 </section>
 <section title="Risk Assessment">
  <p>
   Attempting to throw exceptions from destructors or deallocation functions can result in undefined behavior, leading to resource leaks or
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/BB.+Definitions#BB.Definitions-denial-of-service">
    denial-of-service attacks
   </a>
   .
  </p>
  <table>
   <tbody>
    <tr>
     <th>
      Rule
     </th>
     <th>
      Severity
     </th>
     <th>
      Likelihood
     </th>
     <th>
      Remediation Cost
     </th>
     <th>
      Priority
     </th>
     <th>
      Level
     </th>
    </tr>
    <tr>
     <td>
      DCL57-CPP
     </td>
     <td>
      Low
     </td>
     <td>
      Likely
     </td>
     <td>
      Medium
     </td>
     <td>
      <strong>
       P6
      </strong>
     </td>
     <td>
      <strong>
       L2
      </strong>
     </td>
    </tr>
   </tbody>
  </table>
 </section>
 <section title="Automated Detection">
  <table>
   <tbody>
    <tr>
     <th>
      Tool
     </th>
     <th>
      Version
     </th>
     <th>
      Checker
     </th>
     <th>
      Description
     </th>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=222953724">
       Astrée
      </a>
     </td>
     <td>
      20.10
     </td>
     <td>
      <strong>
       destructor-without-noexcept
       delete-without-noexcept
      </strong>
     </td>
     <td>
      Fully checked
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/Axivion+Bauhaus+Suite">
       Axivion Bauhaus Suite
      </a>
     </td>
     <td>
      7.2.0
     </td>
     <td>
      <strong>
       CertC++-DCL57
      </strong>
     </td>
     <td>
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/Helix+QAC">
       Helix QAC
      </a>
     </td>
     <td>
      2021.2
     </td>
     <td>
      <strong>
       C++2045, C++2047, C++4032, C++4631
      </strong>
     </td>
     <td>
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/Klocwork">
       Klocwork
      </a>
     </td>
     <td>
      2021.4
     </td>
     <td>
      <strong>
       MISRA.DTOR.THROW
      </strong>
     </td>
     <td>
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/LDRA">
       LDRA tool suite
      </a>
     </td>
     <td>
     </td>
     <td>
      <strong>
       453 S
      </strong>
     </td>
     <td>
      Partially implemented
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/Parasoft">
       Parasoft C/C++test
      </a>
     </td>
     <td>
      2021.2
     </td>
     <td>
      <strong>
       CERT_CPP-DCL57-a
      </strong>
      <strong>
       CERT_CPP-DCL57-b
      </strong>
     </td>
     <td>
      Never allow an exception to be thrown from a destructor, deallocation, and swap
      Always catch exceptions
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/Polyspace+Bug+Finder">
       Polyspace Bug Finder
      </a>
     </td>
     <td>
      R2021b
     </td>
     <td>
      <a href="https://www.mathworks.com/help/bugfinder/ref/certcdcl57cpp.html">
       CERT C++: DCL57-CPP
      </a>
     </td>
     <td>
      Checks for class destructors exiting with an exception (rule partially covered)
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/PVS-Studio">
       PVS-Studio
      </a>
     </td>
     <td>
      7.16
     </td>
     <td>
      <strong>
       <a href="https://pvs-studio.com/en/docs/warnings/v509/">
        V509
       </a>
       ,
       <a href="https://pvs-studio.com/en/docs/warnings/v1045/">
        V1045
       </a>
      </strong>
     </td>
     <td>
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/RuleChecker">
       RuleChecker
      </a>
     </td>
     <td>
      20.10
     </td>
     <td>
      <strong>
       destructor-without-noexcept
      </strong>
      <strong>
       delete-without-noexcept
      </strong>
     </td>
     <td>
      Fully checked
     </td>
    </tr>
   </tbody>
  </table>
 </section>
 <section title="Related Vulnerabilities">
  <p>
   Search for
   <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/BB.+Definitions#BB.Definitions-vulnerab">
    vulnerabilities
   </a>
   resulting from the violation of this rule on the
   <a href="https://www.kb.cert.org/vulnotes/bymetric?searchview&amp;query=FIELD+KEYWORDS+contains+DCL57-CPP">
    CERT website
   </a>
   .
  </p>
 </section>
 <section title="Related Guidelines">
  <table>
   <tbody>
    <tr>
     <td>
      <a href="https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=637">
       SEI CERT C++ Coding Standard
      </a>
     </td>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR55-CPP.+Honor+exception+specifications">
       ERR55-CPP. Honor exception specifications
      </a>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR50-CPP.+Do+not+abruptly+terminate+the+program">
       ERR50-CPP. Do not abruptly terminate the program
      </a>
     </td>
    </tr>
    <tr>
     <td>
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-MISRA08">
       MISRA C++:2008
      </a>
     </td>
     <td>
      Rule 15-5-1 (Required)
     </td>
    </tr>
   </tbody>
  </table>
 </section>
 <section title="Bibliography">
  <table>
   <tbody>
    <tr>
     <td>
      [
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-Henricson97">
       Henricson 1997
      </a>
      ]
     </td>
     <td>
      Recommendation 12.5, Do not let destructors called during stack unwinding throw exceptions
     </td>
    </tr>
    <tr>
     <td>
      [
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-ISO%2FIEC14882-2014">
       ISO/IEC 14882-2014
      </a>
      ]
     </td>
     <td>
      Subclause 3.4.7.2, "Deallocation Functions"
      Subclause 15.2, "Constructors and Destructors"
      Subclause 15.3, "Handling an Exception"
      Subclause 15.4, "Exception Specifications"
     </td>
    </tr>
    <tr>
     <td>
      [
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-Meyers05">
       Meyers 2005
      </a>
      ]
     </td>
     <td>
      Item 8, "Prevent Exceptions from Leaving Destructors"
     </td>
    </tr>
    <tr>
     <td>
      [
      <a href="https://wiki.sei.cmu.edu/confluence/display/cplusplus/AA.+Bibliography#AA.Bibliography-Sutter00">
       Sutter 2000
      </a>
      ]
     </td>
     <td>
      "Never allow exceptions from escaping destructors or from an overloaded
      <code>
       operator delete()
      </code>
      " (p. 29)
     </td>
    </tr>
   </tbody>
  </table>
 </section>
</qhelp>